---
- name: install Chocolatey package
  win_chocolatey:
   name: chocolatey
   state: latest
 
- name: Install OSSEC Agent
  win_chocolatey:
    name: ossec-client 
    state: latest

- name: Copy Powershell
  win_copy:
    src: windows.ps1
    dest: C:\

- name: remove server keys
  win_file:
    path: 'C:\Program Files (x86)\ossec-agent\client.keys'
    state: 'absent'

- name: Touch a file (creates if not present, updates modification time if present)
  win_file:
    path: C:\Program Files (x86)\ossec-agent\client.keys
    state: touch

- name: client_keys from ansible server to agent
  win_copy:
    src: /tmp/client.keys
    dest: C:\Program Files (x86)\ossec-agent\tmp\client.keys
  register: keys

- name: Run remote PowerShell Script
  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\windows.ps1


#- name: Crop client key
#  win_shell: |
#     Get-Content 'C:\Program Files (x86)\ossec-agent\tmp\client.keys' | ? { $_ -match "{{ansible_hostname}}" } | | Set-Content C:\Program Files (x86)\ossec-agent\client.keys

- name: remove server keys
  win_file:
    path: 'C:\Program Files (x86)\ossec-agent\tmp\client.keys'
    state: 'absent'
#- name: start ossec
#  service:
#    name: 'ossec'
#    state: 'started'
